// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.2
// source: sshProto.proto

package firmware_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FirmwareDeviceClient is the client API for FirmwareDevice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FirmwareDeviceClient interface {
	ChangeType(ctx context.Context, in *ChangeTypeRequest, opts ...grpc.CallOption) (*ChangeTypeResponse, error)
	Change(ctx context.Context, in *ChangeRequest, opts ...grpc.CallOption) (*ChangeResponse, error)
}

type firmwareDeviceClient struct {
	cc grpc.ClientConnInterface
}

func NewFirmwareDeviceClient(cc grpc.ClientConnInterface) FirmwareDeviceClient {
	return &firmwareDeviceClient{cc}
}

func (c *firmwareDeviceClient) ChangeType(ctx context.Context, in *ChangeTypeRequest, opts ...grpc.CallOption) (*ChangeTypeResponse, error) {
	out := new(ChangeTypeResponse)
	err := c.cc.Invoke(ctx, "/SshTftfProto.FirmwareDevice/ChangeType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *firmwareDeviceClient) Change(ctx context.Context, in *ChangeRequest, opts ...grpc.CallOption) (*ChangeResponse, error) {
	out := new(ChangeResponse)
	err := c.cc.Invoke(ctx, "/SshTftfProto.FirmwareDevice/Change", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FirmwareDeviceServer is the server API for FirmwareDevice service.
// All implementations must embed UnimplementedFirmwareDeviceServer
// for forward compatibility
type FirmwareDeviceServer interface {
	ChangeType(context.Context, *ChangeTypeRequest) (*ChangeTypeResponse, error)
	Change(context.Context, *ChangeRequest) (*ChangeResponse, error)
	mustEmbedUnimplementedFirmwareDeviceServer()
}

// UnimplementedFirmwareDeviceServer must be embedded to have forward compatible implementations.
type UnimplementedFirmwareDeviceServer struct {
}

func (UnimplementedFirmwareDeviceServer) ChangeType(context.Context, *ChangeTypeRequest) (*ChangeTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeType not implemented")
}
func (UnimplementedFirmwareDeviceServer) Change(context.Context, *ChangeRequest) (*ChangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Change not implemented")
}
func (UnimplementedFirmwareDeviceServer) mustEmbedUnimplementedFirmwareDeviceServer() {}

// UnsafeFirmwareDeviceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FirmwareDeviceServer will
// result in compilation errors.
type UnsafeFirmwareDeviceServer interface {
	mustEmbedUnimplementedFirmwareDeviceServer()
}

func RegisterFirmwareDeviceServer(s grpc.ServiceRegistrar, srv FirmwareDeviceServer) {
	s.RegisterService(&FirmwareDevice_ServiceDesc, srv)
}

func _FirmwareDevice_ChangeType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirmwareDeviceServer).ChangeType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SshTftfProto.FirmwareDevice/ChangeType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirmwareDeviceServer).ChangeType(ctx, req.(*ChangeTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FirmwareDevice_Change_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FirmwareDeviceServer).Change(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SshTftfProto.FirmwareDevice/Change",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FirmwareDeviceServer).Change(ctx, req.(*ChangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FirmwareDevice_ServiceDesc is the grpc.ServiceDesc for FirmwareDevice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FirmwareDevice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SshTftfProto.FirmwareDevice",
	HandlerType: (*FirmwareDeviceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ChangeType",
			Handler:    _FirmwareDevice_ChangeType_Handler,
		},
		{
			MethodName: "Change",
			Handler:    _FirmwareDevice_Change_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sshProto.proto",
}
